[package]
name = "voxelizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[[bin]]
name = "voxelize"
path = "src/bin/voxelize.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.2", features = ["derive"] }
nalgebra = "0.32"
rand = "0.8"
